# Generated by Django 5.2 on 2025-05-03 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_fee_paid_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='receipt_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('UPI', 'UPI'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
