# Generated by Django 3.2.25 on 2024-08-31 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0002_auto_20240831_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ENQUIRY', to=settings.AUTH_USER_MODEL),
        ),
    ]
