# Generated by Django 5.2 on 2025-05-05 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0003_period_errorlog_timetableentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nouapp.subject'),
        ),
    ]
