# Generated by Django 3.2.25 on 2024-08-31 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='admin',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
