# Generated by Django 5.2 on 2025-05-07 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0005_alter_timetableentry_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nouapp.teacher'),
        ),
    ]
