# Generated by Django 3.2.25 on 2024-08-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0006_auto_20240831_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_detailed',
            field=models.BooleanField(default=False),
        ),
    ]
