# Generated by Django 3.2.25 on 2025-04-15 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0008_auto_20250415_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='year',
            name='fees',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=50, null=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='nouapp.year')),
            ],
        ),
    ]
