# Generated by Django 3.2.25 on 2025-04-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0014_auto_20250416_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
    ]
