# Generated by Django 3.2.25 on 2025-04-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0015_remove_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default='1st Year', max_length=50),
        ),
    ]
