# Generated by Django 3.2.25 on 2025-04-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0018_auto_20250416_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='aadhar_image',
            new_name='aadhar_imag',
        ),
    ]
