# Generated by Django 3.2.25 on 2025-04-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0019_rename_aadhar_image_student_aadhar_imag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('guest', 'Guest')], default='guest', max_length=10),
        ),
    ]
