# Generated by Django 3.2.25 on 2025-04-16 17:44

from django.db import migrations, models
import django.db.models.deletion
import nouapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0021_entrance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='fee_status',
        ),
        migrations.RemoveField(
            model_name='year',
            name='fees',
        ),
        migrations.AlterField(
            model_name='assesment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nouapp.branch'),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nouapp.program'),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nouapp.year'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nouapp.branch'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nouapp.program'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nouapp.year'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nouapp.branch'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nouapp.program'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nouapp.year'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=nouapp.models.avatar_upload_path),
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='nouapp.feestype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='nouapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='feestype',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_types', to='nouapp.year'),
        ),
    ]
