# Generated by Django 3.2.25 on 2025-04-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0022_auto_20250416_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_eligible_for_admission',
            field=models.BooleanField(default=False),
        ),
    ]
