# Generated by Django 3.2.25 on 2025-04-17 23:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0025_teacher_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.CreateModel(
            name='TeacherInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nouapp.branch')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nouapp.program')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_teachers', to='nouapp.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='nouapp.teacher')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nouapp.year')),
            ],
            options={
                'unique_together': {('teacher', 'subject', 'year', 'branch', 'program')},
            },
        ),
    ]
