# Generated by Django 3.2.25 on 2025-04-18 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0026_auto_20250418_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrance',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrance_exams', to='nouapp.branch'),
        ),
        migrations.AddField(
            model_name='entrance',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrance_exams', to='nouapp.program'),
        ),
        migrations.AddField(
            model_name='feestype',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees_types', to='nouapp.branch'),
        ),
        migrations.AddField(
            model_name='feestype',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees_types', to='nouapp.program'),
        ),
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='nouapp.branch'),
        ),
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='nouapp.program'),
        ),
    ]
